### PR TITLE
Enable invites by default, and add access flags for +i channels

### PR DESCRIPTION
**Pull request by progval**

### CODE REVIEW

**Comment by spb** [comment]
I'm not convinced about this one - the current behaviour matches solanum (except for +g not being implemented) which I think is a more relevant behaviour reference than any of the servers that behave as this PR does.

**Comment by progval** [comment]
> the current behaviour matches solanum

It doesn't. With the default config, even ops cannot invite.

**Comment by spb** [comment]
OK, the current intended behaviour modulo a silly bug caused by forgetting a set of flags - the point being that whether +i is currently set isn't a factor in deciding ability to invite.

**Comment by progval** [comment]
Since the "Remove invite access flags from no-ops by default" commit, this PR fixes the config bug (so it behaves like Solanum by default) and provides the option to configure Sable to allow invites by non-ops (so it can behave like other IRCds)

**Comment by spb** [comment]
Right, but the two sets of invite flags is additional complexity that I don't really see the benefit from - "invite only when the channel isn't invite only" doesn't seem like a useful permission to have given that most channels don't flip +i on and off multiple times a day. Mode +g is a more intuitive way to configure invite permissions IMO (and more familiar to existing Libera users).

**Comment by progval** [comment]
Ok, fair. I'll open another PR with only the config change

**Pull request closed without merging**
